### ISSUE TITLE
major seven triangle issue

### ISSUE THREAD

**Issue by baloe** [microtherion/lilyjazz2#1]
Do you have a sample output somewhere of what the chord test page is expected to look like?
I installed your lilyjazz2 package into my lilypond 2.19.82 installation and when I compile the test file without morejazz, then I always get a traingle symbol for major 7s, though it doesn't quite match the font. When activating morejazz then I get an appropriate traingle symbol in measure 6 but not in 96 and 97.

**Comment by microtherion** [comment]
Thanks for your interest! I've uploaded the PDF now. Page 1 shows the chords with the `morejazz` package, page 2 with the original lilyjazz2 chords (using M7 instead of the triangle, and some other variations from my preferred look). The inappropriate triangles in 96 and 97 are due to these chords not being listed in the original chord name exceptions, which made lilypond fall back to its default algorithm.
To be fair, I don't recall ever having seen Maj7#11 and Maj7#11(13) in the wild.

**Comment by baloe** [comment]
> To be fair, I don't recall ever having seen Maj7#11 and Maj7#11(13) in the wild.

indeed
